version: "3.9"

services:
  api:
    container_name: treasury_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
    networks:
      - appnet

  frontend:
    container_name: treasury_frontend
    build:
      context: ./ttb-label-review-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://treasury_api:8080
    depends_on:
      - api
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
